server:
  port: ${SERVER_PORT:8000}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/traffic_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: ${JWT_SECRET:change-this-dev-secret-change-this-dev-secret}
    access-token-expire-days: ${ACCESS_TOKEN_EXPIRE_DAYS:7}
  network:
    base-url-api: ${BASE_URL_API:http://localhost:8000}
  traffic:
    roads: ${TRAFFIC_ROADS:Đường Trần Hưng Đạo,Đường Trần Phú,Đường Nguyễn Huệ,Đường Lê Lợi,Đường Nguyễn Trãi}
